#!/usr/bin/env bash
TRACER="`uglifyjs tracer.js | perl -wpe 's/([\\"])/\\\\$1/g'`"
TRACER="${TRACER:6:-1}"

#TRACER="{callstack:[{}],descended:false,step:function(log,db){var error=log.getError();if(error!==undefined){this.fault(log,db);return}var syscall=(log.op.toNumber()&240)==240;if(syscall){var op=log.op.toString()}if(syscall&&(op==\\\"CALL\\\"||op==\\\"CALLCODE\\\"||op==\\\"DELEGATECALL\\\"||op==\\\"STATICCALL\\\")){var to=toAddress(log.stack.peek(1).toString(16));if(isPrecompiled(to)){return}var off=op==\\\"DELEGATECALL\\\"||op==\\\"STATICCALL\\\"?0:1;var inOff=log.stack.peek(2+off).valueOf();var inEnd=inOff+log.stack.peek(3+off).valueOf();var call={type:op,from:toHex(log.contract.getAddress()),to:toHex(to),gasIn:log.getGas(),gasCost:log.getCost(),outOff:log.stack.peek(4+off).valueOf(),outLen:log.stack.peek(5+off).valueOf()};if(op!=\\\"DELEGATECALL\\\"&&op!=\\\"STATICCALL\\\"){call.value=\\\"0x\\\"+log.stack.peek(2).toString(16)}this.callstack.push(call);this.descended=true;return}},fault:function(log,db){if(this.callstack[this.callstack.length-1].error!==undefined){return}var call=this.callstack.pop();call.error=log.getError();if(call.gas!==undefined){call.gas=\\\"0x\\\"+bigInt(call.gas).toString(16);call.gasUsed=call.gas}delete call.gasIn;delete call.gasCost;delete call.outOff;delete call.outLen;var left=this.callstack.length;if(left>0){if(this.callstack[left-1].calls===undefined){this.callstack[left-1].calls=[]}this.callstack[left-1].calls.push(call);return}this.callstack.push(call)},result:function(ctx,db){var result={type:ctx.type,from:toHex(ctx.from),to:toHex(ctx.to),value:\\\"0x\\\"+ctx.value.toString(16),gas:\\\"0x\\\"+bigInt(ctx.gas).toString(16),gasUsed:\\\"0x\\\"+bigInt(ctx.gasUsed).toString(16),output:toHex(ctx.output),time:ctx.time};if(this.callstack[0].calls!==undefined){result.calls=this.callstack[0].calls}if(this.callstack[0].error!==undefined){result.error=this.callstack[0].error}else if(ctx.error!==undefined){result.error=ctx.error}if(result.error!==undefined){delete result.output}return this.finalize(result)},finalize:function(call){var sorted={type:call.type,from:call.from,to:call.to,value:call.value,gas:call.gas,gasUsed:call.gasUsed,output:call.output,error:call.error,time:call.time,calls:call.calls};for(var key in sorted){if(sorted[key]===undefined){delete sorted[key]}}if(sorted.calls!==undefined){for(var i=0;i<sorted.calls.length;i++){sorted.calls[i]=this.finalize(sorted.calls[i])}}return sorted}}"
echo $TRACER

GOOD="0x7f45c16fc26ae4d4db9a03508edaa9e8f53a15cb2dcd50fe5b1b728a7a50835b"
BAD="0xa20db1a5477951a9723005fce7d08fb08ccd1e5865ddc9dcd6622a699c1c46bb"

curl --data "{\"id\":\"5533d80c-d7f7-4ed7-9a7a-e0609920c476\",\"jsonrpc\":\"2.0\",\"method\":\"debug_traceTransaction\",\"params\":[\"$GOOD\",{\"timeout\":\"500s\",\"tracer\":\"$TRACER\"}]}" -H 'Content-Type: application/json' -X POST 10.42.77.13:8547
